### ISSUE TITLE
Update root choicelist for navbar

### ISSUE THREAD

**Issue by hduchesne** [Jahia/bootstrap4#10]
It would be great to be able to select our custom root from a page picker. For that I would like to have a new choice in the root choicelist which enable the mixin below.
```
[bootstrap4mix:customNavbarRoot] > jmix:templateMixin mixin
 extends = bootstrap4nt:navbar
 - customRoot (weakreference, picker[type='page']) < 'jnt:page'
```

**Comment by pvollenweider** [comment]
Committed on both master and JAHIA-74 branches
