### ISSUE TITLE
Add id or name to btn-link to be able to use them in jExp goals

### ISSUE THREAD

**Issue by hduchesne** [Jahia/bootstrap4#13]
I created a button (collapse) to display or not a Form.

![lien_btn_collapse](https://user-images.githubusercontent.com/55382113/83860604-c2aa8000-a71f-11ea-998b-6f125c3cf1a6.png)

I want to create a Goals in jExperience to track click on this collapse.

![link_ID_jExp](https://user-images.githubusercontent.com/55382113/83860418-870fb600-a71f-11ea-82f1-34091d4d870e.png)

But, to be able to track the action jExperience needs a ID or a Name into the link and for now we don't have one.
So, we have to :

- option 1 : define an arbitrary ID/Name

- option 2 : offer a field in the contributor UI to fill an id or a name to the link.

Maybe option 2 is better because the link ID has to be "stable" in the time in order to keep the tracking history safe.

![code_btn_collapse](https://user-images.githubusercontent.com/55382113/83860659-d6ee7d00-a71f-11ea-9f64-ec842f0a33fa.png)

**Comment by pvollenweider** [comment]
Commited in https://github.com/Jahia/bootstrap4/commit/eca6c275d73637edbe528e2da9484713e703a8d4
