### ISSUE TITLE
language switch html structure and css

### ISSUE THREAD

**Issue by hduchesne** [Jahia/bootstrap4#14]
Hi,
I tested the new switch language bar and it is very helpful !
However, I think it could have an issue in the HTML generated which use a` <a class="nav-link">` instead of a button. The result with the default BS4 css is the following :
![swith_with_link](https://user-images.githubusercontent.com/55382113/84406537-f434b700-ac09-11ea-8376-eef64609aaef.png)
The link in the language switcher use the primary color and I am not sure it is the expected color for this element.
If you use a button you have this result :
![swith_with_btn](https://user-images.githubusercontent.com/55382113/84406656-2219fb80-ac0a-11ea-84fd-ec5faf68461c.png)
So you don't need to write a specific css and the color of the button is the default color of the text...
The code with the button is that one :
```
<div class="btn-group">
    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        FR
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="#">EN</a>
    </div>
</div>
```

**Comment by pvollenweider** [comment]
I'm not sure to understand the benefit as this language switching is part of the navbar and no other button are set (for login menu or any other link).
Maybe adding a CSS class name on the DIV with dropdown  is more versatile.

**Comment by hduchesne** [comment]
yes we can have this option.
