### ISSUE TITLE
Brand should have a brand-mobile logo property

### ISSUE THREAD

**Issue by hduchesne** [Jahia/bootstrap4#15]
Hi,
Bootstrap is used to design responsive website, and most of them have 2 different logo, one for large screen and one for mobile screen.
So I think it should be useful to have a property available by default in the Brand mixin to manage mobile logo.

**Comment by pvollenweider** [comment]
Commited on 
https://github.com/Jahia/bootstrap4/commit/e933a1f15deb715cd0088af12acab795301bc197
https://github.com/Jahia/bootstrap4/commit/0671220e120e338c0c65c421b0fe6f05b093ffb9
