### ISSUE TITLE
curentPageNode is not manage properly in navigation

### ISSUE THREAD

**Issue by hduchesne** [Jahia/bootstrap4#2]
`<c:set var="curentPageNode" value="${jcr:getMeAndParentsOfType(renderContext.mainResource.node,'jnt:page')}"/>`
return an array but is not managed as his.

e.g. If I create this hierarchy Page Lvl0 -> Lvl1 -> Lvl2

if I add a _navbar_ in Lvl2 and select _currentPage_ as starting point, curentPageNode is equals to `[node /sites/i8/lvl0/lvl1/lvl2, node /sites/i8/lvl0/lvl1, node /sites/i8/lvl0]`

to fix this we have to check if currentPage is not empty and extract the first element
```
<c:if test="${fn:length(curentPageNode) > 0}">
    <c:set var="curentPageNode" value="${curentPageNode[0]}"/>
</c:if>
```

**Comment by pvollenweider** [comment]
Why not this?
`<c:set var="curentPageNode" value="${renderContext.mainResource.node}"/>`

**Comment by hduchesne** [comment]
I thought about it, but if mainRessource is not a page, we can be in trouble.
after we can also do a test...

**Comment by pvollenweider** [comment]
Please test my pull request #3  or create a new one if needed.

**Comment by hduchesne** [comment]
works

**Comment by pvollenweider** [comment]
I closed this PR; the link for to parent page (site node) does not work. Maybe we should link to the homepage.

**Comment by pvollenweider** [comment]
Please check if PR #4  fix this issue
