### ISSUE TITLE
Migration BootstrapV3 -> V4 : some missing components...

### ISSUE THREAD

**Issue by spw-dtic** [Jahia/bootstrap4#7]
We are migrating our references Jahia templates from Bootstrap V3 to BootstrapV4.

Definition :
```

[bootstrap3nt:navBarItemLanguageSwitcher] > jnt:content, bootstrap3mix:navBarItem, jmix:studioOnly
 - typeOfDisplay (string, choicelist[resourceBundle]) = 'isoLocaleCountryCode' mandatory indexed=no < 'isoLocaleCountryCode', 'languageCode', 'doubleLetter', 'letter', 'nameInLocale', 'nameCurrentLocale', 'flag'

```
in file:
[BootstrapV3 definition](https://github.com/Jahia/bootstrap3/blob/master/bootstrap3-components/src/main/resources/META-INF/definitions.cnd)

[Associated view](https://github.com/Jahia/bootstrap3/blob/master/bootstrap3-components/src/main/resources/bootstrap3nt_navBarItemLanguageSwitcher/html/navBarItemLanguageSwitcher.jsp)

But there is no equivalent in Boostrap V4... is it possible to add it in the V4 standard components?
Regards,

REM: same problem for bootstrap3nt:navBarItemLoginForm, bootstrap3nt:navBarItemSimpleSearchForm, etc... that are not migrated.

**Comment by pvollenweider** [comment]
The v4 implementation is a complete refactoring and is not supposed to be ISO to the v3
However, adding a way to switch between languages could be a nice improvement for the navbar. I will add it to the backlog.

**Comment by pvollenweider** [comment]
This has been added in commit https://github.com/Jahia/bootstrap4/commit/e81e1a9c2608d450390b1f8ddbc4cfd95c19f5f5
